name: stroll
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.4 <4.0.0'  # Added upper bound constraint

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/Core/Assets/Images/back.png  
    - lib/Core/Assets/Images/pfp.png 
    - lib/Core/Assets/Images/fade.png 
    - lib/Core/Assets/Fonts/proxima.otf